__build_info:
  rime_version: 1.17.0
  timestamps:
    default: 1784198044
    default.custom: 0
config_version: 2026.07
menu:
  page_size: 9
schema_list:
  - schema: weike_pinyin
  - schema: weike_t9